services:
  db:
    build: ./db
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: Warren
      POSTGRES_PASSWORD: LikeSugarOnMyTongue
      POSTGRES_DB: Archyl_dbTelegram
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
